### ISSUE TITLE
http refused

### ISSUE THREAD

**Issue by matisok** [DIYDave/ScrollText-ESP8266#4]
Dear Dave,

Sorry to bother you but I am trying to build your scroll text using the same setup as you have in your build. I managed to get it working and the matrix display shows the startup animations.

In the serial monitor I can see that the ESP gets an IP address on my local network that I then try in my browser - but it gives a "connection refused" error. Any idea of what I am missing?

Mathias

Serial Monitor Output
```
*WM: [2] Connecting as wifi client... 
*WM: [3] STA static IP:
*WM: [2] setSTAConfig static ip not set, skipping 
*WM: [1] Connecting to SAVED AP: wifirup
*WM: [3] Using Password: zxczxczxc
*WM: [3] WiFi station enable 
*WM: [3] enableSTA PERSISTENT ON 
*WM: [1] connectTimeout not set, ESP waitForConnectResult... 
*WM: [2] Connection result: WL_CONNECTED
*WM: [3] lastconxresult: WL_CONNECTED
*WM: [1] AutoConnect: SUCCESS 
*WM: [1] STA IP Address: 192.168.86.26

```

**Comment by DIYDave** [comment]
Hi Mathias
The ESP itself does not provide a website. He accesses a web server in which the PHP script is running. 
For me this is e.g. my NAS. But any web server at a provider can be used. 
To write a new text you also browse to the same site.

I also have a version that hosts its own website on the ESP. 
But it was just an simple attempt without catching errors or have a nice website. :-)

If there is no other way for you, I'll look for this other version.
Dave
